### ISSUE TITLE
Unnecessary check for existing registry

### ISSUE THREAD

**Issue by tiduseQ** [dapnii/Performance-Booster-Powershell-Script#1]
https://github.com/dapnii/Performance-Booster-Powershell-Script/blob/fd757fbd6d267f3b38f26ca8feaa2b2fbb564c18/PerformanceScript.ps1#L67C1-L72C2

Don't check if reg exists. It might not (for whatever reason) and that would stop adding registries. Your reg add has /f anyway to force it.

**Comment by tiduseQ** [comment]
Same here in entire loop through profiles.
https://github.com/dapnii/Performance-Booster-Powershell-Script/blob/fd757fbd6d267f3b38f26ca8feaa2b2fbb564c18/PerformanceScript.ps1#L78C1-L78C1

**Comment by dapnii** [comment]
Fixed.
